/* 
 * Postgresql schema file for Alchemy::Blog 
 * $Date: 2005/01/02 03:08:23 $
 */

/* bg_sections replaced by bg_blogs -- DELETED. */
create sequence "bg_sections_seq";
create table "bg_sections" (
 	id				int4 PRIMARY KEY DEFAULT NEXTVAL( 'bg_sections_seq' ),
	parent_id 		int4, /* the parent category, 0 for toplevel */
	article_limit	int2, /* max articles to view at once, 0 for no limit */
	s_options		int4, /* boolean options for blog */
	ident			varchar,
	name			varchar,
	frame			varchar,
	language		varchar,
	description 	text
);

/* Replaces bg_sections -- NEW */
create sequence "bg_blog_seq";
create table "bg_blogs" (
 	id				int4 PRIMARY KEY DEFAULT NEXTVAL( 'bg_sections_seq' ),
	options			int4, /* boolean options for blog */
	entry_limit		int2, /* max entries to view at once, 0 for no limit */
	isdefault		bool, /* Is this the default blog */
	identlength		int2, /* How long to limit the idents in this blog */
	comment_live	int2, /* How long you can post comments for */
	ident			varchar,
	name			varchar,
	frame			varchar,
	language		varchar,
	description 	text
);

/* UPDATED */
create sequence "bg_categories_seq";
create table "bg_categories" (
 	id				int4 PRIMARY KEY DEFAULT NEXTVAL( 'bg_categories_seq' ),
/*	bg_section_id	int4, */
	bg_blog_id		int4,
	parent_id 		int4, /* the parent category, 0 for toplevel */
/*	c_options		int4,  boolean options for category */
	options			int4, /* boolean options for category */
/*	article_limit	int2,   max articles to view at once, 0 for no limit */
	entry_limit		int2, /* max articles to view at once, 0 for no limit */
	visible			int2, /* 1 for visible, 0 for not... */
	ident 			varchar,
	frame 			varchar,
	name 			varchar,
	description		text
);

/* NEW */
create sequence "bg_entry_types_seq";
create table "bg_entry_types" (
 	id			int4 PRIMARY KEY DEFAULT NEXTVAL( 'bg_entry_types_seq' ),
	name 		varchar,
	summary_fmt	text,
	entry_fmt	text,
	archive_fmt	text /* Is archive format needed ? */
);

/* replace bg_articles -- NEW */
create sequence "bg_entries_seq";
create table "bg_entries" (
 	id					int4 PRIMARY KEY DEFAULT NEXTVAL( 'bg_entries_seq' ),
	bg_blog_id			int4, /* The blog this belongs to.  */
	bg_entry_type_id 	int4,
	bg_author_id 		int4,
	bg_category_id		int4, /* This is the primary category */
	comment_count 		int4,
	comment_live		int2, /* How long you can post comments for */
	options				int4, /* boolean options for article */
	published 			bool, /* if this type is a live article */
	ident				varchar,
	title 				varchar,
	pub_date 			timestamp with time zone,
	created 			timestamp with time zone,
	modified 			timestamp with time zone,
	excerpt				text, /* Used for a summary */
	content				text
);

/* Entries that are related to this entry -- NEW */
create table "bg_entry_related" (
	bg_entry_id			int4,
	related_entry_id	int4
);

/* entry to category relation, for more than one category. -- NEW */
create table "bg_entry_category" (
	bg_category_id 	int4, 
	bg_entry_id 	int4
);

/* NEW */
/* Not sure that I like this .... */
/* How would this handle a "popup" image ? */
/* For "extra" article items */
create sequence "bg_entry_files_seq";
create table "bg_entry_files" (
 	id				int4 PRIMARY KEY DEFAULT NEXTVAL( 'bg_entry_files_seq' ),
	bg_entry_id 	int4,		/* Article assigned to */
	piece_type		int4, 		/* this may in fact be very redundant. */
		/* 0 for img, 1 for popup inline, 2 for popup view, 3 for other */
	inline			int2, 		/* Is this inline */
	file_name		varchar,	/* The filename */
	include_html	text		
		/* html to put inline, generated by the application as well as
		 * user input. Not directly editable by the user unless they
		 * pick an "other" type of piece. */
);

/* No change to the authors table -- UNCHANGED */
create sequence "bg_authors_seq";
create table "bg_authors" (
 	id		int4 PRIMARY KEY DEFAULT NEXTVAL( 'bg_authors_seq' ),
	ident 	varchar, 
	name 	varchar,
	email 	varchar,
	photo 	varchar,
	bio 	text
);

/* Which blogs they can add to -- NEW  */
create table "bg_author_blogs" (
	bg_author_id 	int4,
	bg_blog_id 		int4,
);

/* Who can be this particular author. -- UNCHANGED */
create table "bg_author_users" (
	author_id 	int4,
	user_id		int4
);

/* REMOVED */
create sequence "bg_article_type_seq";
create table "bg_article_type" (
 	id			int4 PRIMARY KEY DEFAULT NEXTVAL( 'bg_article_type_seq' ),
	published 	bool, /* if this type is a live article */
	name 		varchar
);

/* Replace by bg_entries -- DELETE */
create sequence "bg_articles_seq";
create table "bg_articles" (
 	id					int4 PRIMARY KEY DEFAULT NEXTVAL( 'bg_articles_seq' ),
	bg_article_type_id 	int4,
	bg_author_id 		int4,
	bg_section_id		int4,
	comment_count 		int4,
	a_options			int4, /* boolean options for article */
	ident				varchar,
	topic 				varchar,
	pub_date 			timestamp with time zone,
	modified 			timestamp with time zone,
	summary				text,
	content				text
);

/* For "extra" article items  -- DELETED */
create sequence "bg_article_pieces_seq";
create table "bg_article_pieces" (
 	id			int4 PRIMARY KEY DEFAULT NEXTVAL( 'bg_article_pieces_seq' ),
	bg_article_id 	int4,		/* Article assigned to */
	piece_type		int4, 		/* this may in fact be very redundant. */
		/* 0 for img, 1 for popup inline, 2 for popup view, 3 for other */
	file_name		varchar,	/* The filename */
	alt_text		varchar, 	/* for image alt tag */
	include_html	text		/* to overide default include html */
);

/* Articles that are related to this article -- DELETED */
create table "bg_article_related" (
	bg_article_id		int4,
	related_article_id	int4
);

/* article to category relation -- DELETED */
create table "bg_article_categories" (
	bg_category_id 	int4, 
	bg_article_id 	int4
);

/* Replaced by bg_comments -- DELETED */
create sequence "bg_article_comments_seq";
create table "bg_article_comments" (
 	id			int4 PRIMARY KEY DEFAULT NEXTVAL( 'bg_article_comments_seq' ),
	bg_article_id 	int4,
	parent_id		int4, /* parent comment */
	user_id 		int4, /* Who posted this if authed */
	approved		int2, 
		/* approval status of comment, 0 un 1 proved, 2 if by admin */
	created			timestamp with time zone,
	post_ip			varchar,
	name			varchar,
	email			varchar,
	url				varchar,
	topic 			varchar, /* unused */
	content 		text
);

/* replaces bg_article_comments -- NEW */
create sequence "bg_comments_seq";
create table "bg_comments" (
 	id				int4 PRIMARY KEY DEFAULT NEXTVAL( 'bg_comments_seq' ),
	bg_blog_id 		int4, /* Which blog this is for */
	bg_entry_id 	int4, /* Which entry this is for */
	parent_id		int4, /* parent comment */
	user_id 		int4, /* Who posted this if authed */
	approved		int2, 
		/* approval status of comment, 0 un 1 proved, 2 if by admin */
	created			timestamp with time zone,
	modified		timestamp with time zone,
	post_ip			varchar,
	name			varchar,
	email			varchar,
	url				varchar,
	topic 			varchar, 
	content 		text
);

/* NEW */
create sequence "bg_changelog_seq";
create table "bg_changelog" (
 	id			int4 PRIMARY KEY DEFAULT NEXTVAL( 'bg_changelog_seq' ),
	user_id		int4, 						/* Who did it */
	created		timestamp with time zone, 	/* When they did it */
	log			text 						/* What they did */
);

/* NEW */
create sequence "bg_notify_seq";
create table "bg_notify" (
 	id			int4 PRIMARY KEY DEFAULT NEXTVAL( 'bg_notify_seq' ),
	blog_id		int4,
	bounces		int2,		/* number of bounces recieved. */
	name		varchar, 	/* their name */
	email		varchar, 	/* their email */
	created		timestamp with time zone,
	modified	timestamp with time zone
);
